[project]
name = "tabekko-suizokukan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dwave-ocean-sdk>=9.1.0",
    "matplotlib>=3.10.7",
    "opencv-python-headless>=4.8.0",
    "streamlit>=1.52.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]
